
-- Migration para criar a tabela notification_queue

CREATE TABLE public.notification_queue (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  recipient_user_id UUID NOT NULL,
  notification_type TEXT NOT NULL, -- ex: 'NEW_ASSIGNMENT', 'NEW_COMMENT'
  payload JSONB, -- ex: {"relato_id": "...", "comment_id": "..."}
  status TEXT NOT NULL DEFAULT 'PENDING', -- PENDING, PROCESSED, FAILED
  attempts INT NOT NULL DEFAULT 0,
  last_attempt_at TIMESTAMPTZ,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  processed_at TIMESTAMPTZ,
  error_message TEXT
);

COMMENT ON TABLE public.notification_queue IS 'Fila de notificações a serem processadas e enviadas aos usuários.';

-- Habilitar RLS
ALTER TABLE public.notification_queue ENABLE ROW LEVEL SECURITY;

-- Políticas de segurança
-- Apenas o serviço (ou administradores) podem ler/escrever na fila.
-- Usaremos a service_role key na nossa Edge Function para isso.
CREATE POLICY "Allow full access to service role" 
ON public.notification_queue
FOR ALL
USING (true)
WITH CHECK (true);

